### ISSUE TITLE
Sail type enum

### ISSUE THREAD

**Issue by tkurki** [SignalK/sailsconfiguration#2]
I threw in some placeholder values: `enum: ["main", "gyb", "spinnaker", "codezero"]`. 

What should we have there?

**Comment by vokkim** [comment]
`genoa`, `gennaker`

**Comment by emilecantin** [comment]
`mizzen`, `yankee`

Also, if we want to be really torough: https://en.wikipedia.org/wiki/Sail-plan

**Comment by gatorcse** [comment]
Will we need a rig type as well (`sloop`, `ketch`, `yawl`, etc.)? Or is there one already?

**Comment by tkurki** [comment]
There is http://signalk.org/specification/0.9.0-SNAPSHOT/doc/vesselsBranch.html#vesselsregexpdesignrigging, but I don't think anyone's used it yet in anger.

**Comment by joabakk** [comment]
It really depends on how fine grained we want it to be. 

If some sort of interaction is possible in the form, how about populating the list of sail types based on selection of rig type? For a fully rigged ship, there are 27 sail types only there. Not to mention a 5-masted barque. 
That way, if you buy a vessel with a rig that is not mentioned, you can add an element to the rig type and a corresponding array of sail types.
Or we could be quite general  (Staysail, Spinnaker, Bermuda, Gaff, Topsail, Square etc)

**Comment by rob42** [comment]
rigid wing sails, code zero, kite ?

**Comment by bergie** [comment]
#3 widens the options a bit (list [from Wikipedia](https://en.wikipedia.org/wiki/Sail_plan#Types_of_sail)):

<img width="618" alt="Screenshot 2022-12-15 at 11 53 42" src="https://user-images.githubusercontent.com/3346/207841322-9311970c-279b-4be7-ad4e-cadcf5ff309a.png">

**Comment by tkurki** [comment]
I think this is fixed for now, we can always add more.
