### ISSUE TITLE
Allow other plugins to update sail states

### ISSUE THREAD

**Issue by bergie** [SignalK/sailsconfiguration#4]
Using the Signal K plugin configuration UI is a somewhat clunky way to record sail changes. It would be good to have the plugin subscribe to updates on sail active / reduced status and make calculations accordingly.

A simplified web UI for changing these records might be nice, but maybe should be done separately from this plugin.

**Comment by tkurki** [comment]
I don't know if you have followed lately server development, but 
- 1.46 introduced openapi schemas for the http api https://demo.signalk.org/admin/openapi/
- we have started with [v2 API with course and resources APIs](https://github.com/SignalK/signalk-server/pull/1477)

As the plugin code now is the only way to update sails state is via this plugin's configuration API, no PUT or delta mechanism for updating anything.

Going forward we'd like to move SK towards "a collection of (HTTP) APis, with deltas (more) for sensor-like data updates". So what I'd do next is to remodel the API, based on the current structure, but for practical, real world use cases like
- "set sail with sails x,y and z in such and such state"
- "reef/unreef sail x"
- "hoist/lower sail y"


When a decent API for these is exposed and documented it should be quick work to do a minimal, mobile friendly html ui, and this would allow apps like Freeboard and AvNav to include panels for doing the same. The new API should be mounted under v2 namespace.

Configuration can maybe use the plugin configuration mechanism as is.

What do you think?

**Comment by htool** [comment]
What about how the sail is set?
A wrongly set sail in windy conditions can make the boat heave too much - make it go slow.

When I saw the [trimmscheibe](https://nvcharts.com/4600/trimmscheibe/) I figured it would make sense to be able to record/recall halyard/sheet settings based on weather conditions.
That resulted in [sail trim(https://www.youtube.com/watch?v=pggxLtiAj-w).
Basically it allows to set enums for adjustable parts of the boat and record the setting for a weather condition.

So on one side setup the enums for movable parts like:
```
main sail halyard marker ['-2','-1','0','1','2']
main sail sheet marker ['blue','yellow','green','red']
```
and then have weather conditions setup as you want:
```
wind: ['<5', '>=5', '>=10', '=>15']
waves: ['flat', 'ripples', 'choppy', 'big waves']
```
And then be able to do an api call with the weather conditions and get back the sails to use and their settings.
The idea of the webapp was also to make it very easy to update the settings using touch/buttons, so no typing.

**Comment by tkurki** [comment]
I don't think anybody's done trim data systematically with SK, but definitely a good idea. Wave state another, related area.

So there's two things here:
- recording sail & rig trim state and conditions
- a "sail trip guide app" => "these are the conditions, this is how you should trim ...and this is how it worked in the past"

**Comment by htool** [comment]
I did the [trim plugin](https://www.npmjs.com/package/signalk-trim-plugin), but the downside was that I was storing the info in a file.
Now with the new api it's ideally stored in SignalK so different apps can read/write the data easily.

**Comment by RichFind** [comment]
Well let's open another can of worms. 
Is there a way to integrate this with polar data files?

On sail type you forgot one, Iron Spinnaker. Every heading is downwind.

**Comment by htool** [comment]
Polar data files obviously play a role, as it should tell you if you, given the same circumstances, are able to get to the same performance.
For certain boats the polar diagrams are a given can be loaded into SignalK.
Other boats would have to create their own. So storing speed info along with sail and rig settings should allow you to 'recall' them given certain conditions.

It's nice if the conditions scale can vary and/or if they can be interpolated to not have too many blanks.
Maybe a certain breakdown would help, eg:
 - Weather conditions (above the water, like air temperature, true wind, humidity, air pressure)
 - Water conditions (current, waves, salt content, temperature)
 - Boat conditions (which sails are up and reef level)
 - Boat settings (wind angle, rig settings, heave)

 Where conditions are not changeable (given) and settings are.

Seeing sail config as condition makes it easy to have polar diagrams for the different configs and be able to compare the output of them to be able to suggest changing sail config.

 Every given condition forms a dimension in the matrix. Some can maybe be converted to a factor on another dimension to make it simpler. Like air temperature, air pressure and humidity can likely be reduced.
 
A path seems tricky to store this info. Storing it as a multidimensional array (conditions) of objects (settings) could work. The object settings would refer to a list of trim-able components  (halyards/sheet) where the actual trim settings are user configurable and free form. Anything goes like colors, numbers, free text to allow someone to express the setting.

**Comment by bergie** [comment]
@tkurki exposing an API sounds indeed like the right thing to do here! Is there already an example out there on how a plugin should register its API _and_ the OpenAPI schemas for it? I'd love to take a stab at that here.
